### ISSUE TITLE
Channels tab aux labels

### ISSUE THREAD

**Issue by NotFastEnuf** [BossHobby/Configurator#1]
AUX_TRAVEL_CHECK can be depreciated

AUX_RATES needs to become AUX_HIGH_RATES for clarity sake

AUX_LEDS_ON - this one needs some discussion.  Technically this is LED_CONTROL feature.  In other words - turning this feature on will allow the led to be switched OFF (not ON) via a switch.  This is because the default state for the LED needs to be on and the default state for an AUX switch is ALWAYS_OFF.  The logic in the code lets the LED be ON when the default selection of ALWAYS_OFF is loaded so that doing nothing produces a normal led experience.  A careful choice of labeling here can provide more clarity.  

AUX_STARTFLIP needs to be re-labeled as AUX_TURTLE

**Comment by bkleiner** [comment]
very outdated at this point, lets open a new one for future renames
