### ISSUE TITLE
Synchronize PID profile displayed to last saved

### ISSUE THREAD

**Issue by jklong03** [BossHobby/Configurator#11]
When quad is first plugged in the values that populate the PID values in Configurator <Rate> <PID Preset> pull-down are not representative of the values actually stored.  For me at least, this causes confusion when I plugin for the first time. 

Recommendation:  
a) add a flag when the profile is saved that can be read on bootup by the configurator such that the label in the configurator <Rates> <PID Preset> reflects the PID values actually stored and displayed rather than the default 5" values.
b) alternatively, make it such that the label is blank and when you select [Load] the stored values and label then display the stored values.

This screen shot shows what I got after saving PID preset for a 65mm whoop, then unplugging and reconnecting. Notice the values and label are defaults, not the actual ones being used.

![Mismatched PIDs](https://user-images.githubusercontent.com/110277/224570699-363fac2f-02de-4090-8858-a1697eca683b.png)

**Comment by bkleiner** [comment]
Ok, i transferred the ticket to the configurator.
i think we should definitely make the default of the dropdown something like "Select..." vs the 5in preset, that should help clear up that situation.
Do you have any suggestions for the tooltip?
