### ISSUE TITLE
Request: Change OSD pilot name in configurator

### ISSUE THREAD

**Issue by DyoGTS** [BossHobby/Configurator#5]
Request to add ability to change OSD pilot/craft name in configurator

**Comment by Noramas** [comment]
My vote 😃

**Comment by chaotixtech** [comment]
Agree

**Comment by bkleiner** [comment]
added in https://github.com/BossHobby/Configurator/commit/0e6a25fd360edc570faef16284da48f0597cd11f
will go live with next release
